build:
    environment:
        php:
            version: 7.2
            version: 7.3
            version: 7.4
    tests:
        override:
            -
                command: 'vendor/bin/phpunit --coverage-clover=clover.xml'
                coverage:
                    file: 'clover.xml'
                    format: 'clover'

filter:
    excluded_paths:
        - 'tests/*'
checks:
    php: true
coding_style:
    php: {  }
